name: voter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Add these lines for our app
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2 # Required for picking images from camera or gallery

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # Added for the app logo

  flutter_lints: ^4.0.0

# Added this section for the app logo
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
